### ISSUE TITLE
Issue posted on server

### ISSUE THREAD

**Issue by cmojarro** [cmojarro/meteorRepo#1]
Your app is crashing. Here's the latest log.

/Users/cmo/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
ReferenceError: Router is not defined
    at app/lib/router.js:1:36
    at app/lib/router.js:8:3
    at /Users/cmo/Desktop/ApplicationDesign/meteorRepo/microscope/.meteor/local/build/programs/server/boot.js:205:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/cmo/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/cmo/Desktop/ApplicationDesign/meteorRepo/microscope/.meteor/local/build/programs/server/boot.js:116:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by cmojarro** [comment]
W20150224-08:50:02.232(-6)? (STDERR)  
W20150224-08:50:02.234(-6)? (STDERR) /Users/cmo/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150224-08:50:02.234(-6)? (STDERR)                        throw(ex);
W20150224-08:50:02.234(-6)? (STDERR)                              ^
W20150224-08:50:02.234(-6)? (STDERR) ReferenceError: Router is not defined
W20150224-08:50:02.234(-6)? (STDERR)     at app/lib/router.js:1:36
W20150224-08:50:02.234(-6)? (STDERR)     at app/lib/router.js:16:3
W20150224-08:50:02.235(-6)? (STDERR)     at /Users/cmo/Desktop/ApplicationDesign/meteorRepo/microscope/.meteor/local/build/programs/server/boot.js:205:10
W20150224-08:50:02.235(-6)? (STDERR)     at Array.forEach (native)
W20150224-08:50:02.235(-6)? (STDERR)     at Function._.each._.forEach (/Users/cmo/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150224-08:50:02.235(-6)? (STDERR)     at /Users/cmo/Desktop/ApplicationDesign/meteorRepo/microscope/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8
W20150224-08:50:06.758(-6)? (STDERR)  
W20150224-08:50:06.760(-6)? (STDERR) /Users/cmo/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150224-08:50:06.760(-6)? (STDERR)                        throw(ex);
W20150224-08:50:06.760(-6)? (STDERR)                              ^
W20150224-08:50:06.763(-6)? (STDERR) ReferenceError: Router is not defined
W20150224-08:50:06.763(-6)? (STDERR)     at app/lib/router.js:1:36
W20150224-08:50:06.763(-6)? (STDERR)     at app/lib/router.js:16:3
W20150224-08:50:06.763(-6)? (STDERR)     at /Users/cmo/Desktop/ApplicationDesign/meteorRepo/microscope/.meteor/local/build/programs/server/boot.js:205:10
W20150224-08:50:06.764(-6)? (STDERR)     at Array.forEach (native)
W20150224-08:50:06.764(-6)? (STDERR)     at Function._.each._.forEach (/Users/cmo/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150224-08:50:06.764(-6)? (STDERR)     at /Users/cmo/Desktop/ApplicationDesign/meteorRepo/microscope/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8
W20150224-08:50:11.181(-6)? (STDERR)  
W20150224-08:50:11.183(-6)? (STDERR) /Users/cmo/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150224-08:50:11.184(-6)? (STDERR)                        throw(ex);
W20150224-08:50:11.184(-6)? (STDERR)                              ^
W20150224-08:50:11.187(-6)? (STDERR) ReferenceError: Router is not defined
W20150224-08:50:11.187(-6)? (STDERR)     at app/lib/router.js:1:36
W20150224-08:50:11.188(-6)? (STDERR)     at app/lib/router.js:16:3
W20150224-08:50:11.188(-6)? (STDERR)     at /Users/cmo/Desktop/ApplicationDesign/meteorRepo/microscope/.meteor/local/build/programs/server/boot.js:205:10
W20150224-08:50:11.188(-6)? (STDERR)     at Array.forEach (native)
W20150224-08:50:11.188(-6)? (STDERR)     at Function._.each._.forEach (/Users/cmo/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150224-08:50:11.188(-6)? (STDERR)     at /Users/cmo/Desktop/ApplicationDesign/meteorRepo/microscope/.meteor/local/build/programs/server/boot.js:116:5

**Comment by cmojarro** [comment]
Your app is crashing. Here's the latest log.

/Users/cmo/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
ReferenceError: Router is not defined
    at app/lib/router.js:16:1
    at app/lib/router.js:31:3
    at /Users/cmo/Desktop/ApplicationDesign/meteorRepo/microscope/.meteor/local/build/programs/server/boot.js:205:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/cmo/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/cmo/Desktop/ApplicationDesign/meteorRepo/microscope/.meteor/local/build/programs/server/boot.js:116:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by cmojarro** [comment]
Keeping up with the code blocks in the book is misleading, at times the blocks are hashed and sometimes the code-block is complete, I am using the downloaded pdf not the online book. The pdf does not have any chapters only sectioned by commits
